# Generated by Django 5.2.7 on 2025-11-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='course',
        ),
    ]
